version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command:
      - sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis:7.0.4
    env_file:
      - ./.env.prod.db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/app/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web
volumes:
  postgres_data:
  redis_data:
  static_volume: