version: '3.7'

services:
  web:
    build: ./app
    command:
      - sh
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/code/app/web
      - static_volume:/code/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:7.0.4
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/app/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  static_volume: